// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB119TLOMLAbvDaIbzqsUlcBEXxeuNnYrA',
    appId: '1:945192510236:web:6ca9ace10ac850756d50d9',
    messagingSenderId: '945192510236',
    projectId: 'clapmi-b6206',
    authDomain: 'clapmi-b6206.firebaseapp.com',
    storageBucket: 'clapmi-b6206.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUpGQX_z8j9KJCs_A-CCbpSQSeRAYD5sY',
    appId: '1:945192510236:android:134637387c1cca546d50d9',
    messagingSenderId: '945192510236',
    projectId: 'clapmi-b6206',
    storageBucket: 'clapmi-b6206.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZwRV5tGj86WS_2BcBtKR1XAY7VW1o9HU',
    appId: '1:945192510236:ios:f2acc234b283011d6d50d9',
    messagingSenderId: '945192510236',
    projectId: 'clapmi-b6206',
    storageBucket: 'clapmi-b6206.firebasestorage.app',
    androidClientId: '945192510236-4admqbl5lgh4ub0hcegbrhf5g8e6mqmm.apps.googleusercontent.com',
    iosClientId: '945192510236-k5bj7im6fjf54rtjhq1kbias2hfr22i4.apps.googleusercontent.com',
    iosBundleId: 'com.clapmi123.app.ClapmiIosScreenshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZwRV5tGj86WS_2BcBtKR1XAY7VW1o9HU',
    appId: '1:945192510236:ios:b75f19bdb9c0f8316d50d9',
    messagingSenderId: '945192510236',
    projectId: 'clapmi-b6206',
    storageBucket: 'clapmi-b6206.firebasestorage.app',
    androidClientId: '945192510236-4admqbl5lgh4ub0hcegbrhf5g8e6mqmm.apps.googleusercontent.com',
    iosClientId: '945192510236-tnuqfshkemtv9bj47r05gio4jsufsc1l.apps.googleusercontent.com',
    iosBundleId: 'com.clapmi123.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARiIDvelWKBAn57zlfZFfkc7SV8SPn4P0',
    appId: '1:945192510236:web:0aec2e6c58c5f6e96d50d9',
    messagingSenderId: '945192510236',
    projectId: 'clapmi-b6206',
    authDomain: 'clapmi-b6206.firebaseapp.com',
    storageBucket: 'clapmi-b6206.firebasestorage.app',
  );
}
